name: Build & Publish

on: release
jobs:
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn -B -DskipTests package --projects agent/war-unsecured --also-make
      
      - uses: JasonEtco/upload-to-release@master
        with:
          args: agent/war-unsecured/target/jolokia-*.war
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
