name: Build & Publish

on:
  push:
    branches:
      - docker-proxy
  release:
    types: [created, edited]
jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dockerfile Build & Publish
        uses: matootie/github-docker@v2.2.3
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          imageTagSuffix: '-patched'
      
      - run: cp agent/war-unsecured/target/jolokia-*.war jolokia.war
      - uses: JasonEtco/upload-to-release@master
        with:
          args: jolokia.war
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
