name: Build & Publish

on:
  push:
    tags:
      - "v*"
jobs:
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn -B -DskipTests package --projects agent/war-unsecured --also-make
      - run: cp -T agent/war-unsecured/target/jolokia-*.war jolokia.war
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            jolokia.war
